import { ReduxProviders } from '@/redux/Providers'
import './globals.css'
import type { Metadata } from 'next'



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ReduxProviders>
          {children}
        </ReduxProviders>
      </body>
    </html>
  )
}
